### ISSUE TITLE
Add an icon for the webpage

### ISSUE THREAD

**Issue by sarahsga** [IjunaidI/weather-app#3]
![screen shot 2018-08-26 at 20 49 49](https://user-images.githubusercontent.com/10798986/44630070-a5088e00-a971-11e8-8fdc-f99e47d8598f.png)

Give an icon to the webpage. 

For example, Facebook has an icon like this:

![screen shot 2018-08-26 at 20 51 12](https://user-images.githubusercontent.com/10798986/44630085-cd908800-a971-11e8-8191-536712827b66.png)

**Comment by IjunaidI** [comment]
Done
